### ISSUE TITLE
MTGNN运行报错

### ISSUE THREAD

**Issue by ZPFPHD** [zezhishao/BasicTS#67]
终端指令：python examples/run.py -c examples/MTGNN/MTGNN_METR-LA.py

2023-08-20 11:17:39,599 - easytorch-training - INFO - Epoch 1 / 10
  0%|                                                                                                                          | 0/192 [00:03<?, ?it/s] 
2023-08-20 11:17:43,446 - easytorch-training - ERROR - Traceback (most recent call last):
  File "D:\anaconda\envs\Basicts\lib\site-packages\easytorch\launcher\launcher.py", line 31, in training_func
  File "D:\pycharmproject\BasicTS-master\basicts\runners\runner_zoo\mtgnn_runner.py", line 109, in train_iters
    loss = super().train_iters(epoch, iter_index, data)
  File "D:\pycharmproject\BasicTS-master\basicts\runners\base_tsf_runner.py", line 276, in train_iters
    forward_return = list(self.forward(data=data, epoch=epoch, iter_num=iter_num, train=True))
    loss = super().train_iters(epoch, iter_index, data)
  File "D:\pycharmproject\BasicTS-master\basicts\runners\base_tsf_runner.py", line 276, in train_iters
    forward_return = list(self.forward(data=data, epoch=epoch, iter_num=iter_num, train=True))
    forward_return = list(self.forward(data=data, epoch=epoch, iter_num=iter_num, train=True))
    prediction_data = self.model(
  File "D:\anaconda\envs\Basicts\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    adp = self.gc(idx)
  File "D:\anaconda\envs\Basicts\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\pycharmproject\BasicTS-master\basicts\archs\arch_zoo\mtgnn_arch\mtgnn_layers.py", line 192, in forward
    s1, t1 = adj.topk(self.k, 1)
RuntimeError: selected index k out of range

这里k值报错，topk存在问题吗？没有研究明白，麻烦指点下，感谢！其他时空模型可以运行，唯独MTGNN报错。

**Comment by From-zero-tohero** [comment]
k超过了节点数量，把K设置小于节点数量就行
