### ISSUE TITLE
ModuleNotFoundError: No module named '.home'

### ISSUE THREAD

**Issue by emanlee** [zezhishao/BasicTS#89]
作者，您好！
我们运行以下这步训练模型（下面加粗的代码），出现错误。 我们之前已经跑过了   python scripts/data_preparation/METR-LA/generate_training_data.py

**python experiments/train.py -c /home/xq/BasicTS-master/baselines/MLP/MLP_METR-LA.py --gpus '0'**
2023-11-12 21:09:25,090 - easytorch-launcher - INFO - Launching EasyTorch training.
Traceback (most recent call last):
  File "/home/xq/BasicTS-master/experiments/train.py", line 25, in <module>
    launch_training(args.cfg, args.gpus)
  File "/home/xq/BasicTS-master/basicts/launcher.py", line 30, in launch_training
    easytorch.launch_training(cfg=cfg, devices=gpus, node_rank=node_rank)
  File "/home/mytool/anaconda3/envs/basicts/lib/python3.9/site-packages/easytorch/launcher/launcher.py", line 59, in launch_training
    cfg = init_cfg(cfg, node_rank == 0)
  File "/home/mytool/anaconda3/envs/basicts/lib/python3.9/site-packages/easytorch/config/utils.py", line 210, in init_cfg
    cfg = import_config(cfg, verbose=save)
  File "/home/mytool/anaconda3/envs/basicts/lib/python3.9/site-packages/easytorch/config/utils.py", line 173, in import_config
    cfg = __import__(path, fromlist=[cfg_name]).CFG
**ModuleNotFoundError: No module named '.home'**

**Comment by zezhishao** [comment]
感谢您的建议！-c后面的路径目前只能支持相对路径，后续我再README中强调一下。

**Comment by emanlee** [comment]
谢谢您的回复！问题解决了。
