### ISSUE TITLE
如何修改数据集预测的时间长度，我修改了生成数据集的参数和模型的参数后存在如下问题

### ISSUE THREAD

**Issue by chenywu** [zezhishao/BasicTS#98]
File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 31, in training_func
    runner.train(cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/core/runner.py", line 349, in train
    self.on_epoch_end(epoch)
  File "/root/BasicTS/basicts/runners/base_runner.py", line 121, in on_epoch_end
    self.test_process(train_epoch=epoch)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/utils/dist.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/root/BasicTS/basicts/runners/base_runner.py", line 147, in test_process
    self.test()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/utils/dist.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/root/BasicTS/basicts/runners/base_tsf_runner.py", line 442, in test
    self.evaluate(returns_all)
  File "/root/BasicTS/basicts/runners/base_tsf_runner.py", line 397, in evaluate
    pred = returns_all["prediction"][:, i, :, :]
IndexError: index 3 is out of bounds for dimension 1 with size 3

Traceback (most recent call last):
  File "experiments/train.py", line 25, in <module>
    launch_training(args.cfg, args.gpus)
  File "/root/BasicTS/basicts/launcher.py", line 30, in launch_training
    easytorch.launch_training(cfg=cfg, devices=gpus, node_rank=node_rank)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 86, in launch_training
    train_dist(cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 35, in training_func
    raise e
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 31, in training_func
    runner.train(cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/core/runner.py", line 349, in train
    self.on_epoch_end(epoch)
  File "/root/BasicTS/basicts/runners/base_runner.py", line 121, in on_epoch_end
    self.test_process(train_epoch=epoch)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/utils/dist.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/root/BasicTS/basicts/runners/base_runner.py", line 147, in test_process
    self.test()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/utils/dist.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/root/BasicTS/basicts/runners/base_tsf_runner.py", line 442, in test
    self.evaluate(returns_all)
  File "/root/BasicTS/basicts/runners/base_tsf_runner.py", line 397, in evaluate
    pred = returns_all["prediction"][:, i, :, :]
IndexError: index 3 is out of bounds for dimension 1 with size 3

**Comment by zezhishao** [comment]
Thanks for your report. That's helpful.

You can add:
```python
# ================= evaluate ================= #
CFG.EVAL = EasyDict()
CFG.EVAL.HORIZONS = [] # the evaluation horizons
```
to the end of your configs.

I just updated BasicTS to change the default evaluation horizons to [], which means BasicTS only calculates metrics at all horizons.
Previously, it was range(1, 13), which means that BasicTS will additionally evaluate each horizon in range(1, 13).
